export const FETCH_ALL_ITEMS = 'FETCH_ALL_ITEMS'

export const GET_ALL_ITEMS = 'GET_ALL_ITEMS'
export const GET_PENDING_ITEMS = 'GET_PENDING_ITEM'
export const GET_COMPLETED_ITEMS = 'GET_COMPLETED_ITEM'
export const TOGGLE_STATUS_ITEM = 'TOGGLE_STATUS_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'

export const RESET_MESSAGE = 'RESET_MESSAGE'
export const SET_MESSAGE = 'SET_MESSAGE'
